name: Security Pipeline
on:
  workflow_call:
    inputs:
      python-poetry:
        description: 'Poetry used to install dependencies'
        required: false
        type: string
        default: 'true'

jobs:
  # Secrets detection is calling the Yelp Secrets Detector we use in pre-commit to ensure proper coverage
  secrets-detection:
    runs-on: 'ubuntu-latest'
    steps:
      - name: secrets detect
        uses: RobertFischer/detect-secrets-action@v2.0.0

      - name: Report Status
        if: failure()
        uses: act10ns/slack@v2.1.0
        with:
          channel: '#infosec-alerts'
          status: ${{ job.status }}
        env:
          webhook-url: ${{ secrets.ACTION_MONITORING_SLACK }}
